# Generated by Django 5.1.15 on 2026-08-11 18:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FaqVector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("pergunta", models.CharField(max_length=500, verbose_name="pergunta")),
                ("resposta", models.TextField(verbose_name="resposta")),
                (
                    "categoria",
                    models.CharField(
                        blank=True,
                        help_text="Agrupador livre (convênios, horários, exames…). Usado só para curadoria.",
                        max_length=50,
                        verbose_name="categoria",
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(
                        default=True,
                        help_text="Somente FAQs ativas são indexadas e consultadas pelo chatbot.",
                        verbose_name="ativa",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True, verbose_name="criado em")),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "embedding_gerado_em",
                    models.DateTimeField(
                        blank=True,
                        help_text="Vazio significa que a linha ainda não tem vetor na coluna EMBEDDING.",
                        null=True,
                        verbose_name="embedding gerado em",
                    ),
                ),
                (
                    "embedding_modelo",
                    models.CharField(
                        blank=True,
                        help_text="Modelo que gerou o vetor. Consultar com outro modelo devolve lixo silencioso.",
                        max_length=100,
                        verbose_name="modelo do embedding",
                    ),
                ),
                (
                    "embedding_dim",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Dimensão do vetor gravado. Deve bater com EMBEDDING_DIM das settings.",
                        null=True,
                        verbose_name="dimensão do embedding",
                    ),
                ),
                (
                    "conteudo_hash",
                    models.CharField(
                        blank=True,
                        help_text="SHA-256 de pergunta+resposta na indexação. É o que torna o reindex idempotente.",
                        max_length=64,
                        verbose_name="hash do conteúdo",
                    ),
                ),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQs",
                "db_table": "FAQ_VECTOR",
                "ordering": ["categoria", "pergunta"],
                "indexes": [models.Index(fields=["ativo"], name="IDX_FAQ_ATIVO")],
            },
        ),
        migrations.CreateModel(
            name="InteracaoChat",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "conversa_id",
                    models.UUIDField(
                        help_text="Agrupa os turnos de uma mesma conversa. Validado contra a sessão (anti-IDOR).",
                        verbose_name="conversa",
                    ),
                ),
                (
                    "sequencia",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Posição do turno dentro da conversa, começando em 1.",
                        verbose_name="sequência",
                    ),
                ),
                ("pergunta", models.TextField(verbose_name="pergunta")),
                ("resposta", models.TextField(blank=True, verbose_name="resposta")),
                (
                    "tools_usadas",
                    models.JSONField(blank=True, default=list, verbose_name="tools usadas"),
                ),
                (
                    "faq_ids",
                    models.JSONField(blank=True, default=list, verbose_name="FAQs consultadas"),
                ),
                ("modelo", models.CharField(blank=True, max_length=100, verbose_name="modelo")),
                (
                    "tokens_entrada",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="tokens de entrada"
                    ),
                ),
                (
                    "tokens_saida",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="tokens de saída"
                    ),
                ),
                (
                    "latencia_ms",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Tempo total do turno. O TTFT é medido à parte, no stream.",
                        null=True,
                        verbose_name="latência (ms)",
                    ),
                ),
                (
                    "alucinacao_detectada",
                    models.BooleanField(default=False, verbose_name="alucinação detectada"),
                ),
                ("erro", models.TextField(blank=True, verbose_name="erro")),
                ("criado_em", models.DateTimeField(auto_now_add=True, verbose_name="criado em")),
            ],
            options={
                "verbose_name": "interação do chat",
                "verbose_name_plural": "interações do chat",
                "db_table": "INTERACAO_CHAT",
                "ordering": ["conversa_id", "sequencia"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("conversa_id", "sequencia"),
                        name="UK_INTERACAO_SEQ",
                        violation_error_message="Esta conversa já tem um turno nesta posição.",
                    )
                ],
            },
        ),
    ]
