# Generated by Django 5.1.15 on 2026-08-11 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Medico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nome", models.CharField(max_length=150, verbose_name="nome")),
                ("crm_numero", models.CharField(max_length=20, verbose_name="número do CRM")),
                ("crm_uf", models.CharField(max_length=2, verbose_name="UF do CRM")),
                (
                    "rqe",
                    models.CharField(
                        blank=True,
                        help_text="Registro de Qualificação de Especialista, quando houver.",
                        max_length=20,
                        verbose_name="RQE",
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(
                        default=True,
                        help_text="Desmarque para tirar da agenda e do chatbot sem apagar o histórico.",
                        verbose_name="ativo",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True, verbose_name="criado em")),
            ],
            options={
                "verbose_name": "médico",
                "verbose_name_plural": "médicos",
                "db_table": "MEDICO",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Especialidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="nome")),
                (
                    "slug",
                    models.SlugField(
                        db_index=False,
                        help_text="Identificador estável usado em URLs e no enum das tools do chatbot.",
                        max_length=100,
                        verbose_name="slug",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(
                        blank=True,
                        help_text="Resumo de uma linha. Limitado a 300 caracteres para não virar NCLOB no Oracle.",
                        max_length=300,
                        verbose_name="descrição",
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(
                        default=True,
                        help_text="Desmarque para tirar do site e do chatbot sem apagar o histórico.",
                        verbose_name="ativa",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True, verbose_name="criado em")),
            ],
            options={
                "verbose_name": "especialidade",
                "verbose_name_plural": "especialidades",
                "db_table": "ESPECIALIDADE",
                "ordering": ["nome"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("nome",),
                        name="UK_ESPECIALIDADE_NOME",
                        violation_error_message="Já existe uma especialidade com este nome.",
                    ),
                    models.UniqueConstraint(
                        fields=("slug",),
                        name="UK_ESPECIALIDADE_SLUG",
                        violation_error_message="Já existe uma especialidade com este slug.",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MedicoEspecialidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "principal",
                    models.BooleanField(
                        default=False,
                        help_text="Especialidade de destaque do médico no site e no chatbot.",
                        verbose_name="principal",
                    ),
                ),
                (
                    "especialidade",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vinculos_medico",
                        to="crm.especialidade",
                        verbose_name="especialidade",
                    ),
                ),
                (
                    "medico",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vinculos_especialidade",
                        to="crm.medico",
                        verbose_name="médico",
                    ),
                ),
            ],
            options={
                "verbose_name": "especialidade do médico",
                "verbose_name_plural": "especialidades do médico",
                "db_table": "MEDICO_ESPECIALIDADE",
                "ordering": ["medico", "-principal", "especialidade"],
            },
        ),
        migrations.AddField(
            model_name="medico",
            name="especialidades",
            field=models.ManyToManyField(
                blank=True,
                related_name="medicos",
                through="crm.MedicoEspecialidade",
                to="crm.especialidade",
                verbose_name="especialidades",
            ),
        ),
        migrations.AddIndex(
            model_name="medicoespecialidade",
            index=models.Index(fields=["especialidade"], name="IDX_MED_ESPEC_ESPEC"),
        ),
        migrations.AddConstraint(
            model_name="medicoespecialidade",
            constraint=models.UniqueConstraint(
                fields=("medico", "especialidade"),
                name="UK_MEDICO_ESPEC",
                violation_error_message="Este médico já está vinculado a esta especialidade.",
            ),
        ),
        migrations.AddConstraint(
            model_name="medico",
            constraint=models.UniqueConstraint(
                fields=("crm_numero", "crm_uf"),
                name="UK_MEDICO_CRM",
                violation_error_message="Já existe um médico com este CRM nesta UF.",
            ),
        ),
    ]
