# Generated by Django 5.1.15 on 2026-08-14 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Paciente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nome", models.CharField(max_length=150, verbose_name="nome")),
                (
                    "cpf_cifrado",
                    models.CharField(
                        help_text="AES-256-GCM. Preenchido apenas por Paciente.definir_cpf().",
                        max_length=255,
                        verbose_name="CPF (cifrado)",
                    ),
                ),
                (
                    "cpf_hash",
                    models.CharField(
                        help_text="HMAC-SHA256 com pepper. Preenchido apenas por Paciente.definir_cpf().",
                        max_length=64,
                        verbose_name="CPF (hash de busca)",
                    ),
                ),
                ("data_nascimento", models.DateField(verbose_name="data de nascimento")),
                ("email", models.EmailField(blank=True, max_length=254, verbose_name="e-mail")),
                ("telefone", models.CharField(blank=True, max_length=20, verbose_name="telefone")),
                (
                    "ativo",
                    models.BooleanField(
                        default=True,
                        help_text="Desmarque para arquivar o paciente sem apagar o histórico (retenção CFM).",
                        verbose_name="ativo",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True, verbose_name="criado em")),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
            ],
            options={
                "verbose_name": "paciente",
                "verbose_name_plural": "pacientes",
                "db_table": "PACIENTE",
                "ordering": ["nome"],
                "indexes": [models.Index(fields=["nome"], name="IDX_PACIENTE_NOME")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("cpf_hash",),
                        name="UK_PACIENTE_CPF_HASH",
                        violation_error_message="Já existe um paciente cadastrado com este CPF.",
                    )
                ],
            },
        ),
    ]
