# Generated by Django 5.1.15 on 2026-08-14 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0003_consulta"),
        ("crm", "0002_paciente"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nome", models.CharField(max_length=150, verbose_name="nome")),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Opcional: o lead começa antes de a pessoa informar contato.",
                        max_length=254,
                        verbose_name="e-mail",
                    ),
                ),
                ("telefone", models.CharField(blank=True, max_length=20, verbose_name="telefone")),
                (
                    "etapa",
                    models.CharField(
                        choices=[
                            ("NOVO", "Novo"),
                            ("QUALIFICADO", "Qualificado"),
                            ("AGENDADO", "Agendado"),
                            ("COMPARECEU", "Compareceu"),
                            ("RETORNO", "Retorno"),
                        ],
                        default="NOVO",
                        max_length=12,
                        verbose_name="etapa",
                    ),
                ),
                (
                    "conversa_id",
                    models.UUIDField(
                        blank=True,
                        help_text="UUID da conversa do chatbot (InteracaoChat.conversa_id) que originou o lead.",
                        null=True,
                        verbose_name="conversa",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True, verbose_name="criado em")),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "consulta",
                    models.ForeignKey(
                        blank=True,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leads",
                        to="agenda.consulta",
                        verbose_name="consulta",
                    ),
                ),
                (
                    "especialidade_interesse",
                    models.ForeignKey(
                        blank=True,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="leads",
                        to="crm.especialidade",
                        verbose_name="especialidade de interesse",
                    ),
                ),
            ],
            options={
                "verbose_name": "lead",
                "verbose_name_plural": "leads",
                "db_table": "LEAD",
                "ordering": ["-id"],
                "indexes": [
                    models.Index(fields=["etapa"], name="IDX_LEAD_ETAPA"),
                    models.Index(fields=["conversa_id"], name="IDX_LEAD_CONVERSA"),
                    models.Index(fields=["especialidade_interesse"], name="IDX_LEAD_ESPECIALIDADE"),
                    models.Index(fields=["consulta"], name="IDX_LEAD_CONSULTA"),
                ],
            },
        ),
    ]
