# Generated by Django 5.1.15 on 2026-08-14 23:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agenda", "0003_consulta"),
        ("crm", "0003_lead"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Prontuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True, verbose_name="criado em")),
                (
                    "paciente",
                    models.OneToOneField(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prontuario",
                        to="crm.paciente",
                        verbose_name="paciente",
                    ),
                ),
            ],
            options={
                "verbose_name": "prontuário",
                "verbose_name_plural": "prontuários",
                "db_table": "PRONTUARIO",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="LogAcesso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "acao",
                    models.CharField(
                        choices=[
                            ("VISUALIZOU", "Visualizou"),
                            ("EXPORTOU", "Exportou"),
                            ("EDITOU", "Editou"),
                        ],
                        max_length=10,
                        verbose_name="ação",
                    ),
                ),
                (
                    "ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="Vazio quando o acesso não veio de uma requisição HTTP.",
                        null=True,
                        verbose_name="IP",
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True,
                        help_text="Truncado em 300 caracteres para não virar NCLOB no Oracle.",
                        max_length=300,
                        verbose_name="user agent",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True, verbose_name="criado em")),
                (
                    "paciente",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="acessos",
                        to="crm.paciente",
                        verbose_name="paciente",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="acessos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "log de acesso",
                "verbose_name_plural": "logs de acesso",
                "db_table": "LOG_ACESSO",
                "ordering": ["-id"],
                "indexes": [
                    models.Index(fields=["paciente"], name="IDX_LOG_ACESSO_PACIENTE"),
                    models.Index(fields=["criado_em"], name="IDX_LOG_ACESSO_DATA"),
                    models.Index(fields=["usuario"], name="IDX_LOG_ACESSO_USUARIO"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Evolucao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "texto",
                    models.TextField(
                        help_text="Registro clínico. Só é lido, nunca filtrado — pode ser CLOB no Oracle.",
                        verbose_name="texto",
                    ),
                ),
                (
                    "conteudo_hash",
                    models.CharField(
                        blank=True,
                        help_text="SHA-256 de texto+autor+timestamp. Preenchido no INSERT; prova de autoria (CFM).",
                        max_length=64,
                        verbose_name="hash do conteúdo",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Carimbo da autoria. Entra no hash, por isso não é auto_now_add.",
                        verbose_name="criado em",
                    ),
                ),
                (
                    "consulta",
                    models.ForeignKey(
                        blank=True,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evolucoes",
                        to="agenda.consulta",
                        verbose_name="consulta",
                    ),
                ),
                (
                    "evolucao_anterior",
                    models.ForeignKey(
                        blank=True,
                        db_index=False,
                        help_text="Preencha ao corrigir ou complementar um registro anterior — é o único caminho de retificação, já que a tabela é append-only.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="correcoes",
                        to="prontuario.evolucao",
                        verbose_name="evolução anterior",
                    ),
                ),
                (
                    "medico",
                    models.ForeignKey(
                        db_index=False,
                        help_text="Autor do registro. Entra no hash de autoria exigido pelo CFM.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evolucoes",
                        to="crm.medico",
                        verbose_name="médico",
                    ),
                ),
                (
                    "prontuario",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evolucoes",
                        to="prontuario.prontuario",
                        verbose_name="prontuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "evolução",
                "verbose_name_plural": "evoluções",
                "db_table": "EVOLUCAO",
                "ordering": ["-id"],
                "indexes": [
                    models.Index(fields=["prontuario"], name="IDX_EVOLUCAO_PRONTUARIO"),
                    models.Index(fields=["medico"], name="IDX_EVOLUCAO_MEDICO"),
                    models.Index(fields=["consulta"], name="IDX_EVOLUCAO_CONSULTA"),
                    models.Index(fields=["evolucao_anterior"], name="IDX_EVOLUCAO_ANTERIOR"),
                ],
            },
        ),
    ]
