# Generated by Django 5.1.15 on 2026-08-11 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgendaSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("data", models.DateField(verbose_name="data")),
                ("hora_inicio", models.TimeField(verbose_name="hora de início")),
                ("hora_fim", models.TimeField(verbose_name="hora de término")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("LIVRE", "Livre"),
                            ("RESERVADO", "Reservado"),
                            ("BLOQUEADO", "Bloqueado"),
                        ],
                        default="LIVRE",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True, verbose_name="criado em")),
                (
                    "medico",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="slots",
                        to="crm.medico",
                        verbose_name="médico",
                    ),
                ),
            ],
            options={
                "verbose_name": "slot de agenda",
                "verbose_name_plural": "slots de agenda",
                "db_table": "AGENDA_SLOT",
                "ordering": ["data", "hora_inicio"],
                "indexes": [models.Index(fields=["data", "status"], name="IDX_SLOT_DATA_STATUS")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("medico", "data", "hora_inicio"),
                        name="UK_SLOT_MEDICO_HORARIO",
                        violation_error_message="Este médico já tem um slot neste dia e horário.",
                    )
                ],
            },
        ),
    ]
