# Generated by Django 5.1.15 on 2026-08-14 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0001_initial"),
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgendaRegra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "dia_semana",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Segunda-feira"),
                            (1, "Terça-feira"),
                            (2, "Quarta-feira"),
                            (3, "Quinta-feira"),
                            (4, "Sexta-feira"),
                            (5, "Sábado"),
                            (6, "Domingo"),
                        ],
                        help_text="0 = segunda … 6 = domingo (mesma convenção de date.weekday()).",
                        verbose_name="dia da semana",
                    ),
                ),
                ("hora_inicio", models.TimeField(verbose_name="hora de início")),
                ("hora_fim", models.TimeField(verbose_name="hora de término")),
                (
                    "duracao_consulta_min",
                    models.PositiveSmallIntegerField(
                        help_text="Tamanho de cada slot gerado, em minutos.",
                        verbose_name="duração da consulta (min)",
                    ),
                ),
                (
                    "intervalo_min",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Folga entre o fim de uma consulta e o início da próxima.",
                        verbose_name="intervalo entre consultas (min)",
                    ),
                ),
                ("vigencia_inicio", models.DateField(verbose_name="início da vigência")),
                (
                    "vigencia_fim",
                    models.DateField(
                        blank=True,
                        help_text="Deixe em branco para regra sem prazo de término.",
                        null=True,
                        verbose_name="fim da vigência",
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(
                        default=True,
                        help_text="Desmarque para parar de gerar slots sem apagar o histórico.",
                        verbose_name="ativa",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True, verbose_name="criado em")),
                (
                    "medico",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="regras",
                        to="crm.medico",
                        verbose_name="médico",
                    ),
                ),
            ],
            options={
                "verbose_name": "regra de agenda",
                "verbose_name_plural": "regras de agenda",
                "db_table": "AGENDA_REGRA",
                "ordering": ["medico", "dia_semana", "hora_inicio"],
            },
        ),
        migrations.AddField(
            model_name="agendaslot",
            name="regra",
            field=models.ForeignKey(
                blank=True,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="slots",
                to="agenda.agendaregra",
                verbose_name="regra de origem",
            ),
        ),
        migrations.AddIndex(
            model_name="agendaslot",
            index=models.Index(fields=["regra"], name="IDX_SLOT_REGRA"),
        ),
        migrations.AddConstraint(
            model_name="agendaregra",
            constraint=models.UniqueConstraint(
                fields=("medico", "dia_semana", "hora_inicio", "vigencia_inicio"),
                name="UK_AGENDA_REGRA_JANELA",
                violation_error_message="Este médico já tem uma regra neste dia da semana, com este horário de início e esta vigência.",
            ),
        ),
        migrations.AddConstraint(
            model_name="agendaregra",
            constraint=models.CheckConstraint(
                condition=models.Q(("hora_fim__gt", models.F("hora_inicio"))),
                name="CK_AGENDA_REGRA_HORARIO",
                violation_error_message="A hora de término tem que ser maior que a de início.",
            ),
        ),
        migrations.AddConstraint(
            model_name="agendaregra",
            constraint=models.CheckConstraint(
                condition=models.Q(("duracao_consulta_min__gt", 0)),
                name="CK_AGENDA_REGRA_DURACAO",
                violation_error_message="A duração da consulta tem que ser maior que zero.",
            ),
        ),
        migrations.AddConstraint(
            model_name="agendaregra",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("vigencia_fim__isnull", True),
                    ("vigencia_fim__gte", models.F("vigencia_inicio")),
                    _connector="OR",
                ),
                name="CK_AGENDA_REGRA_VIGENCIA",
                violation_error_message="O fim da vigência não pode ser antes do início.",
            ),
        ),
    ]
