# Generated by Django 5.1.15 on 2026-08-14 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0002_agendaregra_agendaslot_regra_and_more"),
        ("crm", "0002_paciente"),
    ]

    operations = [
        migrations.CreateModel(
            name="Consulta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AGENDADA", "Agendada"),
                            ("CONFIRMADA", "Confirmada"),
                            ("REALIZADA", "Realizada"),
                            ("CANCELADA", "Cancelada"),
                            ("FALTOU", "Faltou"),
                        ],
                        default="AGENDADA",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                (
                    "origem",
                    models.CharField(
                        choices=[("CHAT", "Chatbot"), ("RECEPCAO", "Recepção"), ("SITE", "Site")],
                        default="RECEPCAO",
                        help_text="RECEPCAO é o caminho manual; CHAT e SITE são preenchidos por quem agenda.",
                        max_length=10,
                        verbose_name="origem",
                    ),
                ),
                (
                    "observacoes",
                    models.CharField(
                        blank=True,
                        help_text="Anotação operacional da recepção. Limitada a 500 caracteres para não virar NCLOB no Oracle. Registro clínico vai em EVOLUCAO.",
                        max_length=500,
                        verbose_name="observações",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True, verbose_name="criado em")),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "medico",
                    models.ForeignKey(
                        db_index=False,
                        help_text="Cópia de slot.medico — preenchida pelo AgendamentoService, não pelo caller.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consultas",
                        to="crm.medico",
                        verbose_name="médico",
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consultas",
                        to="crm.paciente",
                        verbose_name="paciente",
                    ),
                ),
                (
                    "slot",
                    models.OneToOneField(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consulta",
                        to="agenda.agendaslot",
                        verbose_name="slot",
                    ),
                ),
            ],
            options={
                "verbose_name": "consulta",
                "verbose_name_plural": "consultas",
                "db_table": "CONSULTA",
                "ordering": ["-id"],
                "indexes": [
                    models.Index(fields=["paciente"], name="IDX_CONSULTA_PACIENTE"),
                    models.Index(fields=["medico"], name="IDX_CONSULTA_MEDICO"),
                    models.Index(fields=["status"], name="IDX_CONSULTA_STATUS"),
                ],
            },
        ),
    ]
